### ISSUE TITLE
Error: %1 non è un'applicazione di Win32 valida.

### ISSUE THREAD

**Issue by Giancarlo1974** [durs/node-activex#1]
I have downloaded your script and then unzipped
When i launch the command:

node Test.js

i got this error:

module.js:460
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: %1 non è un'applicazione di Win32 valida.
\?\D:\activex\Release\activex.node
    at Error (native)
    at Object.Module._extensions..node (module.js:460:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (D:\Banche\activex\Test.js:8:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)

I use Windows 10, Python27, and Visual studio 2015
Can you help me?

**Comment by durs** [comment]
Sorry, this is an example of an outdated and probably with a new version of
the node.js does not work.

2016-02-11 14:29 GMT+03:00 Giancarlo1974 <notifications@github.com>:

**Comment by Giancarlo1974** [comment]
There is hope to see an updated code?

Unfortunately I have not found any library to manage DCOM through Node.js

A real pity :-(

**Comment by durs** [comment]
Today I corrected binaries only for version NodeJS <= 0.10.26

New versions are not compatible with this extension format

And while I did not understand how to work with them


2016-02-12 12:22 GMT+03:00 Giancarlo1974 <notifications@github.com>:
