### ISSUE TITLE
32bit OCX

### ISSUE THREAD

**Issue by nulldreams** [durs/node-activex#14]
**Hi!**
**Winax** doesnt have support for 32 bit **dll/ocx?**

I mean, I have two DLLs, one of which has 32-bit and 64-bit versions, the other DLL `NFSeX.spdNFSeX` has only a 32-bit version and the object is not being created 😭

**Code:**
```
const ActiveX = require('winax')
const spdNFCe = new ActiveX.Object('NFSeX.spdNFSeX')
```

**Error:**
```
const spdNFCe = new ActiveX.Object('NFSeX.spdNFSeX')
                ^

Error: CreateInstance: NFSeX.spdNFSeX Class not registered

    at Object.<anonymous> (C:\Documentação\SaaS\componente\node\app.js:2:17)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
```
**PS:** The DLL is registered, but as 32 bits

**Comment by durs** [comment]
Hi, 32-bit dll may be used only with 32-bit node.exe

2017-08-22 17:06 GMT+03:00 Igor Souza Martins <notifications@github.com>:

**Comment by nulldreams** [comment]
Thank you, the problem is in my dll 😕
Sorry!
